version: 2
    
jobs:
  deploy:
    docker:
      - image: circleci/node:12.12.0
      
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "Mine77@users.noreply.github.com"
            git config --global user.name "Mine77"
            yarn install && yarn deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
