version: 2
    
jobs:
  deploy:
    docker:
      - image: circleci/node:11.11.0
      
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command:
            yarn install && yarn deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master